# Generated by Django 3.2 on 2023-04-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, max_length=100, verbose_name='Nome social do profissional')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.CharField(max_length=100, verbose_name='Nome do paciente')),
                ('nome_social', models.CharField(blank=True, max_length=100, verbose_name='Nome social do paciente')),
                ('data_consulta', models.DateField(verbose_name='Data da consulta')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='consultas.profissional', verbose_name='Nome do profissional')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
